---
# tasks file for config_web
- name: "Install webserver httpd"
  package:
          name: httpd
          state: present
          

- name: "copy index.html file "
  copy:
          src: "index.html"
          dest: "/var/www/html"

- name: "start service"
  service:
          name: httpd
          state: started
- name: "Allow http over firewall"
  firewalld:
          port: 80/tcp
          state: enabled
          permanent: yes
          immediate: yes

